### PR TITLE
Added talks from symposium

### PR DESCRIPTION
**Pull request by narock**
Uploaded pdf versions of all the talks.

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @narock do you want me to embed these into the Symposium Webpage? Thanks for gathering them all up.

**Comment by narock** [comment]
@lewismc I already added links to the talk in the symposium agenda page: https://esipfed.github.io/stc/symposium_schedule.html  That's probably enough.

**Comment by lewismc** [comment]
dynamite, I didn't see that. Thanks Tom.

**Comment by narock** [comment]
@lewismc I just made another commit, but the pull request option isn't showing up for me on GitHub. Can you see it? It was a change in the last few minutes to fix an incorrect talk title.

**Comment by lewismc** [comment]
No I don't see it either. Did you commit directly to master or to symposium branch... or some other branch maybe?

**Comment by narock** [comment]
@lewismc it was committed to the symposium2017 branch. It's here: https://github.com/ESIPFed/stc/commit/6b9025b9a88339903a1f840047e0f629ff4ce8ec but I can't figure out why I can't merge.

**Pull request merged**
